class EstudioContableNotFoundError(Exception):
    """Custom exception for Estudios-Contables."""
    pass